### ISSUE TITLE
Remove unnecessary javascript files

### ISSUE THREAD

**Issue by khaliddpdev** [khalidhoffman/PetAdoption-Wordpress#9]
[`page-stubs.js`](https://github.com/khalidhoffman/PetAdoption-Wordpress/blob/master/public/js/modules/pages-stub.js) and [`views.json`](https://github.com/khalidhoffman/PetAdoption-Wordpress/blob/master/public/js/modules/views.json) are never used

**Comment by khalidhoffman** [comment]
resolved with f66cb1dd3a8bebc74c0f095e5182beb77f4c7bf2
